### DISCUSSION TITLE
Ability to configure the entityManagerPath for resolver code generation?

### DISCUSSION THREAD

**Discussion by Atlinx** [twinlogix/typetta#197] [Q&A] [answered]
I found the `entityManagerPath` option in the generator source code, however, I can't seem to set it inside my `typetta.yml` file. I've seen the `codegenConfig` config option in docs for the code generator settings, but I don't know how to make it work.

Here's my attempt in my yaml file.
```yaml
schema: src/**.typedefs.ts
outputDir: src/generated
generateGraphQLOperations:
  resolvers:
    codegenConfig: {
      entityManagerPath: "test_path"       
    }
```
