### DISCUSSION TITLE
Import typescript schema files instead of just parsing them.

### DISCUSSION THREAD

**Discussion by Atlinx** [twinlogix/typetta#222] [Ideas]
Typetta currently does not import typescript schema files but instead parses them. This prevents users from building graphql schemas through typescript code.

So something like this doesn't work. Typetta doesn't pick up the injected query type.
```typescript
const someVar = `
type Query {
  myCustomQuery(arg: String!): Boolean
}
` 

export default gql`
type User @entity @mongodb ]
  ...
}

${someVar}
`
```

Having typetta pick up the custom generated schemas is useful because typetta generate typescript types for the graphql it reads.

**Comment by minox86** [comment]
This comes from graphql-code-generator, that we use internally. Anyway your
issue could be interesting.

We will investigate this possibility for sure.

Il Sab 28 Mag 2022, 18:51 Atlinx ***@***.***> ha scritto:

**Reply by Atlinx** [reply]
Maybe [the `noPluck` config option](https://www.graphql-code-generator.com/docs/config-reference/schema-field#nopluck) can enable the use of the `require` behaviour? I can't seem to fit this into the `typetta.yml` config though.

I've tried this, which didn't work:
```yml
schema: 'src/**.typedefs.ts'
outputDir: src/generated
generateGraphQLOperations:
  operations:
    codegenConfig:
      schema:
        - 'src/**.typedefs.ts':
          noPluck: true
          noRequire: false
  resolversTypes:
    codegenConfig:
      schema:
        - 'src/**.typedefs.ts':
          noPluck: true
      noPluck: true
  resolvers:
    codegenConfig:
      schema:
        - 'src/**.typedefs.ts':
          noPluck: true
  context: 
    path: entityManager
```
